#SOAP Service Details cloudhub
#oms.soap.host=https://order-management-soap-service-m7euhp.5sc6y6-4.usa-e2.cloudhub.io
soap.address=https://order-management-soap-service-v2-m7euhp.5sc6y6-2.usa-e2.cloudhub.io/OrderManagementService/OrderManagementServiceSoap11

#localhost
#soap.address=http://localhost:8082/OrderManagementService/OrderManagementServiceSoap11
http.port=8081
api.id=21165560